server:
  port: 8080

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: RESTURANT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/resturantdb
    username: khadija
    password: 112233
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect